name: Dynamic Job Creation Workflow

on:
    push:
        branches:
            - main


jobs:
    generate_matrix:
        runs-on: ubuntu-latest
        outputs:
            projects: ${{ steps.projects.outputs.projects }}
        steps:
            - uses: actions/checkout@v4

            - name: Generate Projects
              id: projects
              run: |
                python generate_matrix.py
                matrix=$(cat matrix.json | jq -c '.')
                echo "projects=$matrix" >> $GITHUB_OUTPUT

    dynamic_jobs:
        needs: generate_matrix
        runs-on: ubuntu-latest
        strategy:
            matrix:
                projects: ${{ fromJson(needs.generate_matrix.outputs.projects).include }}

        steps:
            - uses: actions/checkout@v4
            - run: chmod +x ./run_task.sh
            - run: ./run_task.sh ${{ matrix.projects.project }}